DB_USERNAME = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_NAME = "vacation_planner"
FB_ACC_PATH = "C:/Users/ryanh/Downloads/vacation-698a8-firebase-adminsdk-fbsvc-61dc104cf9.json"
MAPBOX_PRIVATE_TOKEN = "KEY"
MAPBOX_PUBLIC_TOKEN = "KEY_GOES_HERE"
