DB_USERNAME = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_NAME = "vacation_planner"
FB_ACC_PATH = "C:/Users/ryanh/Downloads/vacation-698a8-firebase-adminsdk-fbsvc-61dc104cf9.json"
MAPBOX_PRIVATE_TOKEN = "sk.eyJ1IjoiY2hlZXNlZnJpZXMiLCJhIjoiY204bmJjc2toMDBnMjJ5cHpkaWQ0aWVldSJ9.j3l4E43PL3P1MKT_KtjUTw"
MAPBOX_PUBLIC_TOKEN = "pk.eyJ1IjoiY2hlZXNlZnJpZXMiLCJhIjoiY204bWNjc2E2MHd6NTJscHJtaWh6bzNwZCJ9.MRSx5fqK2n6vuZPz3TOz2w"
